Add html to match wireframes
INF6420/ss23-RaynasDad pull request #3
Opened 2023-06-04 02:50 UTC by RaynasDad

2023-06-05 13:58 UTC, axamei requested changes
please add the images to the `src` attribute of the `img` tag. 

book an appointment if you need assistance.

2023-06-07 03:22 UTC, RaynasDad commented
@axamei This really confused me, because I had already added all these images in the img tags.  (I forgot to hit Save.)  Thankfully, it was all still in my code editor.

2023-06-07 13:59 UTC, axamei requested changes
There are a few more pages missing images that you need to save and commit.

2023-06-07 13:59 UTC, axamei commented on about.html
> +        <img src="" alt="Archibald Family Website logo">
Image missing

2023-06-07 13:59 UTC, axamei commented on about.html
> +        <img src="" alt="fancy About image">
Image missing

2023-06-07 13:59 UTC, axamei commented on about.html
> +    <img src="" alt="Archibald Family footer image">
Image missing

2023-06-07 13:59 UTC, axamei commented on index.html
> +        <img src="" alt="Archibald Family Website logo">
Image missing

2023-06-07 13:59 UTC, axamei commented on index.html
> +        <img src="" alt="Archibald Family Photo">
Image missing

2023-06-07 13:59 UTC, axamei commented on index.html
> +                <img src="" alt="picture of Matt">
Image missing

2023-06-07 13:59 UTC, axamei commented on index.html
> +                <img src="" alt="picture of Jenn">
Image missing

2023-06-07 13:59 UTC, axamei commented on index.html
> +                <img src="" alt="picture of Julia">
Image missing

2023-06-07 13:59 UTC, axamei commented on index.html
> +                <img src="" alt="picture of Rayna">
Image missing

2023-06-07 13:59 UTC, axamei commented on index.html
> +                <img src="" alt="picture of Josiah">
Image missing

2023-06-07 13:59 UTC, axamei commented on index.html
> +                <img src="" alt="picture of Skye">
Image missing

2023-06-07 13:59 UTC, axamei commented on index.html
> +    <img src="" alt="Archibald Family footer image">
Image missing

2023-06-07 13:59 UTC, axamei commented on matt.html
> +        <img src="images/family crest.jpg" alt="Archibald Family crest">
Please rename the image to not include spaces, e.g., `family-crest.jpg`

2023-06-07 13:59 UTC, axamei commented on matt.html
> +        <img src="images/may the fork be with you.jpg" alt="picture of Matt with Yoda on his shoulder, holding up a fork that says 'may the fork be with you'">
Please rename the image to not include spaces

2023-06-07 13:59 UTC, axamei commented on matt.html
> +                <img src="images/singing at Barns.jpg" alt="picture of Matt holding a guitar, singing at a microphone with Rayna and Jenn">
Please rename the image to not include spaces

2023-06-07 13:59 UTC, axamei requested changes
There are a few more pages missing images that you need to save and commit.

2023-06-07 16:45 UTC, RaynasDad commented
@axamei Ugh!  Sorry!  I think I have them all now.  I guess I assumed that I was saving the whole project, not just the page I was on.

2023-06-07 19:07 UTC, axamei approved these changes

2023-06-07 19:07 UTC, merged